// Generated by scripts/estate/pack.mjs from the pack it describes. Do not edit:
// rebuild the pack instead (docs/portfolio/estate-pack.md).
// DEV PACK — built with --dev-src, provenance unchecked; never commit or publish.

export const ESTATE_CATALOGUE = {
  edition: "v1.2",
  packUrl: "/estate/v1.2/pack.2fa7069b.json",
  commit: "0000000000000000000000000000000000000000",
  dev: true,
  poster: { src: "/estate/v1.2/poster/aerial-800.28d835c8.jpg", srcSet: "/estate/v1.2/poster/aerial-800.7d4a5c0e.webp 800w, /estate/v1.2/poster/aerial-1600.f5c2d707.webp 1600w", w: 1600, h: 1200, alt: "Still render of Sample Town N5 from the north-east: a generated sample HDB neighbourhood, not a real town." },
  flats: 1206,
  storeys: 245,
  sites: [
    { id: "BLK_501", name: "Blk 501", kind: "block", typology: "PT4", heightM: 60.2, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","RF"], facade: { bytes: 59456 }, detail: { bytes: 20566 }, interior: { bytes: 30346 }, walk: { bytes: 7900 }, nav: { bytes: 7887 } },
    { id: "BLK_502", name: "Blk 502", kind: "block", typology: "PT4", heightM: 60.2, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","RF"], facade: { bytes: 61578 }, detail: { bytes: 19713 }, interior: { bytes: 29062 }, walk: { bytes: 7880 }, nav: { bytes: 7823 } },
    { id: "BLK_503", name: "Blk 503", kind: "block", typology: "PT4", heightM: 65.8, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","L21","L22","RF"], facade: { bytes: 68543 }, detail: { bytes: 21276 }, interior: { bytes: 29571 }, walk: { bytes: 7382 }, nav: { bytes: 8309 } },
    { id: "BLK_504", name: "Blk 504", kind: "block", typology: "PT4", heightM: 65.8, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","L21","L22","RF"], facade: { bytes: 66642 }, detail: { bytes: 20598 }, interior: { bytes: 30070 }, walk: { bytes: 7357 }, nav: { bytes: 8285 } },
    { id: "BLK_505", name: "Blk 505", kind: "block", typology: "PT4", heightM: 74.2, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","L21","L22","L23","L24","L25","RF"], facade: { bytes: 69309 }, detail: { bytes: 22277 }, interior: { bytes: 30372 }, walk: { bytes: 7300 }, nav: { bytes: 9147 } },
    { id: "BLK_506", name: "Blk 506", kind: "block", typology: "PT4", heightM: 74.2, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","L17","L18","L19","L20","L21","L22","L23","L24","L25","RF"], facade: { bytes: 73630 }, detail: { bytes: 22769 }, interior: { bytes: 31845 }, walk: { bytes: 7808 }, nav: { bytes: 9160 } },
    { id: "BLK_507", name: "Blk 507", kind: "block", typology: "SL", heightM: 43.4, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","RF"], facade: { bytes: 70096 }, detail: { bytes: 17219 }, interior: { bytes: 39987 }, walk: { bytes: 12618 }, nav: { bytes: 11059 } },
    { id: "BLK_508", name: "Blk 508", kind: "block", typology: "SL", heightM: 43.4, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","RF"], facade: { bytes: 71819 }, detail: { bytes: 17177 }, interior: { bytes: 38575 }, walk: { bytes: 13011 }, nav: { bytes: 11062 } },
    { id: "BLK_509", name: "Blk 509", kind: "block", typology: "SL", heightM: 49, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","RF"], facade: { bytes: 85736 }, detail: { bytes: 21153 }, interior: { bytes: 47837 }, walk: { bytes: 16727 }, nav: { bytes: 14584 } },
    { id: "BLK_510", name: "Blk 510", kind: "block", typology: "LB", heightM: 49, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","RF"], facade: { bytes: 90692 }, detail: { bytes: 28213 }, interior: { bytes: 53751 }, walk: { bytes: 23490 }, nav: { bytes: 12871 } },
    { id: "BLK_511", name: "Blk 511", kind: "block", typology: "LB", heightM: 49, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","L13","L14","L15","L16","RF"], facade: { bytes: 99792 }, detail: { bytes: 27962 }, interior: { bytes: 53640 }, walk: { bytes: 23409 }, nav: { bytes: 13093 } },
    { id: "BLK_512", name: "Blk 512", kind: "block", typology: "SL", heightM: 37.8, storeys: ["L1","L2","L3","L4","L5","L6","L7","L8","L9","L10","L11","L12","RF"], facade: { bytes: 54317 }, detail: { bytes: 12585 }, interior: { bytes: 32804 }, walk: { bytes: 12958 }, nav: { bytes: 8295 } },
    { id: "MSCP_513", name: "Multi-storey car park 513", kind: "mscp", typology: null, heightM: 28.04, storeys: ["L1","L2","L3","L4","L5","L6","L7","RF"], facade: { bytes: 24210 }, detail: { bytes: 2684 }, interior: { bytes: 17329 }, walk: { bytes: 26828 }, nav: { bytes: 8295 } },
    { id: "NC_514", name: "Sample Town N5 neighbourhood centre", kind: "nc", typology: null, heightM: 9.3, storeys: ["L1","L2","RF"], facade: { bytes: 12788 }, detail: { bytes: 6384 }, interior: { bytes: 30105 }, walk: { bytes: 13763 }, nav: { bytes: 3213 } },
  ],
  bytes: {"stage0":84409,"poster":292142,"s0":69248,"f":908608,"d":260576,"i":495294,"w":188431,"nav":133083,"ground":8011,"total":2421622},
} as const;

export type EstateCatalogue = typeof ESTATE_CATALOGUE;
