// Generated by scripts/estate/pack.mjs from the pack it describes. Do not edit:
// rebuild the pack instead (docs/portfolio/estate-pack.md).
// Bonsai-Estate v1.2 @ a6e1acf603c69b7bc9a34a72c8f6b92081268932.

export const ESTATE_CATALOGUE = {
  edition: "v1.2",
  packUrl: "/estate/v1.2/pack.4a3c0883.json",
  commit: "a6e1acf603c69b7bc9a34a72c8f6b92081268932",
  dev: false,
  poster: { src: "/estate/v1.2/poster/aerial-800.53f2560a.jpg", srcSet: "/estate/v1.2/poster/aerial-800.0660a80c.webp 800w, /estate/v1.2/poster/aerial-1600.04327dbd.webp 1600w", w: 1600, h: 1200, alt: "Still render of Sample Town N5 from the north-east: a generated sample HDB neighbourhood, not a real town." },
  flats: 1206,
  storeys: 245,
  sites: [
    { id: "BLK_501", name: "Blk 501", kind: "block", typology: "PT4", heightM: 60.2, levels: "L1–L20 + RF" },
    { id: "BLK_502", name: "Blk 502", kind: "block", typology: "PT4", heightM: 60.2, levels: "L1–L20 + RF" },
    { id: "BLK_503", name: "Blk 503", kind: "block", typology: "PT4", heightM: 65.8, levels: "L1–L22 + RF" },
    { id: "BLK_504", name: "Blk 504", kind: "block", typology: "PT4", heightM: 65.8, levels: "L1–L22 + RF" },
    { id: "BLK_505", name: "Blk 505", kind: "block", typology: "PT4", heightM: 74.2, levels: "L1–L25 + RF" },
    { id: "BLK_506", name: "Blk 506", kind: "block", typology: "PT4", heightM: 74.2, levels: "L1–L25 + RF" },
    { id: "BLK_507", name: "Blk 507", kind: "block", typology: "SL", heightM: 43.4, levels: "L1–L14 + RF" },
    { id: "BLK_508", name: "Blk 508", kind: "block", typology: "SL", heightM: 43.4, levels: "L1–L14 + RF" },
    { id: "BLK_509", name: "Blk 509", kind: "block", typology: "SL", heightM: 49, levels: "L1–L16 + RF" },
    { id: "BLK_510", name: "Blk 510", kind: "block", typology: "LB", heightM: 49, levels: "L1–L16 + RF" },
    { id: "BLK_511", name: "Blk 511", kind: "block", typology: "LB", heightM: 49, levels: "L1–L16 + RF" },
    { id: "BLK_512", name: "Blk 512", kind: "block", typology: "SL", heightM: 37.8, levels: "L1–L12 + RF" },
    { id: "MSCP_513", name: "Multi-storey car park 513", kind: "mscp", typology: null, heightM: 28.04, levels: "L1–L7 + RF" },
    { id: "NC_514", name: "Sample Town N5 neighbourhood centre", kind: "nc", typology: null, heightM: 9.3, levels: "L1–L2 + RF" },
  ],
  bytes: {"stage0":84711,"f":953855},
} as const;

export type EstateCatalogue = typeof ESTATE_CATALOGUE;
