import { expect, test, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

// The desk drawing set on the production build (docs/portfolio/desk-drawing-set.md):
// the default desktop background. At 1920 × 1080 the boot windows leave the desk's
// bottom band free, so the drawing reads there behind them; at 1280 × 720 they
// cover the desk and it parks, downloading nothing but its layer; DESK uncovers the
// desk and plays the film. Reduced motion and Save-Data get one still cover and
// never the film; ?mode=scan keeps the plain grid. The drawing's own frames are
// counted by the stack of each requestAnimationFrame call (its film chunk), so the
// rest of the page cannot muddy them.

const DRAWING_CHUNK = /\/assets\/(DeskBackdropLayer|DrawingField|drawingFilm)-[\w-]+\.js$/;
const SHEET_CHUNK = /\/assets\/[A-Z]+_\d+\.generated-[\w-]+\.js$/;
const ENGINE_CHUNKS = /\/assets\/(?:estate-engine|estate-shared|estate-bench|EstateHud)-[\w-]+\.js$/;
const CREDIT = 'Sample Town N5 © Rahul Mitra, CC BY 4.0, generated by Bonsai-Estate';

const collectErrors = (page: Page) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
  return errors;
};

const collectPaths = (page: Page) => {
  const paths: string[] = [];
  page.on('request', (request) => paths.push(new URL(request.url()).pathname));
  return paths;
};

/** Counts the requestAnimationFrame calls the drawing's film makes (by the chunk on the stack). */
const countDrawingFrames = (page: Page) => page.addInitScript(() => {
  const counted = window as Window & { __drawingRaf?: number };
  counted.__drawingRaf = 0;
  const raf = window.requestAnimationFrame.bind(window);
  window.requestAnimationFrame = (callback) => {
    if (/drawingFilm-/.test(new Error().stack ?? '')) counted.__drawingRaf = (counted.__drawingRaf ?? 0) + 1;
    return raf(callback);
  };
});
const drawingFrames = (page: Page) => page.evaluate(() => (window as Window & { __drawingRaf?: number }).__drawingRaf ?? 0);

const booted = (page: Page) => page.waitForFunction(() => document.readyState === 'complete' && !document.querySelector('.fi-root'), undefined, { timeout: 30_000 });
const drawing = (page: Page) => page.locator('.wb-drawing');
const desk = (page: Page) => page.evaluate(() => document.querySelector<HTMLButtonElement>('.wb-rail-desk')!.click());
const traverse = (page: Page) => page.getByRole('toolbar', { name: 'Drawing sheets' });
const sheet = (page: Page) => drawing(page).getAttribute('data-drawing-sheet');

/** The station Next lands on: the first drawable one after the sheet on show (from the opening aerial, the first of all). */
const nextStation = (page: Page) => traverse(page).evaluate((bar) => {
  const stations = [...bar.querySelectorAll('.wb-drawing-nav-stn')];
  const opening = /:(R0|W)$/.test(document.querySelector<HTMLElement>('.wb-drawing')!.dataset.drawingSheet ?? '');
  const at = opening ? -1 : stations.findIndex((s) => s.hasAttribute('aria-current'));
  return stations.find((s, i) => i > at && s.getAttribute('aria-disabled') !== 'true')?.textContent ?? null;
});

test.describe('desk drawing set', () => {
  test.describe.configure({ timeout: 90_000 });

  test('at 1920 × 1080 reads behind the boot windows, sleeps between sheets, credits the data and fetches nothing of the Estate', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await countDrawingFrames(page);
    const errors = collectErrors(page);
    const paths = collectPaths(page);
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-mode', 'reading', { timeout: 20_000 });
    await expect(drawing(page)).toHaveAttribute('data-drawing-state', 'running');
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 20_000 });
    const before = await drawingFrames(page);
    await page.waitForTimeout(1000);
    expect(await drawingFrames(page) - before, 'drawing frames in 1 s of a hold').toBe(0);
    // The canvas stays clear of every open window.
    const overlap = await page.evaluate(() => {
      const canvas = document.querySelector('canvas[data-drawing-canvas]')!.getBoundingClientRect();
      return [...document.querySelectorAll<HTMLElement>('section[data-win]')].filter((w) => w.style.display !== 'none').some((w) => {
        const r = w.getBoundingClientRect();
        return canvas.left < r.right && r.left < canvas.right && canvas.top < r.bottom && r.top < canvas.bottom;
      });
    });
    expect(overlap).toBe(false);
    await expect(page.locator('.wb-drawing-chip')).toContainText(CREDIT);
    await expect(page.locator('.wb-drawing-chip')).toContainText('not a real town or HDB’s own plans');
    expect(paths.filter((p) => p.startsWith('/estate/') && !p.includes('/poster/'))).toEqual([]);
    expect(paths.filter((p) => ENGINE_CHUNKS.test(p))).toEqual([]);
    expect(errors).toEqual([]);
  });

  test('DESK plays the film: the welcome where the Estate poster was, then the site plan; the title plate holds its height', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-mode', 'reading', { timeout: 20_000 });
    const plateBefore = await page.locator('.wb-plate').boundingBox();
    await desk(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-mode', 'desk', { timeout: 10_000 });
    await expect(drawing(page)).toHaveAttribute('data-drawing-sheet', /:W$/);
    const lines = page.locator('.wb-plate-slot .wb-plate-lines span');
    await expect(lines.first()).toHaveText('07 OF 07 · ESTATE AERIAL NE');
    await expect(lines.nth(1)).toHaveText(/^GENERATED SAMPLE · (LIVE|HELD|STILL)$/);
    const heights: number[] = [];
    heights.push((await page.locator('.wb-plate').boundingBox())!.height);
    await expect(drawing(page)).toHaveAttribute('data-drawing-sheet', /:S1$/, { timeout: 20_000 });
    await expect(lines.first()).toHaveText(/^01 OF 0[67] · .+ SITE$/);
    heights.push((await page.locator('.wb-plate').boundingBox())!.height);
    expect(Math.abs(heights[0] - heights[1])).toBeLessThan(0.5);
    expect(plateBefore).not.toBeNull();
    // The shortcuts stay usable over the drawing: a real pointer click, which a host
    // that took pointer events would swallow.
    await page.getByRole('list', { name: 'Desktop shortcuts' }).getByRole('button', { name: 'Open Home / Dossier' }).click();
    await expect(page.locator('section[data-win="home"]')).toBeVisible();
  });

  test('at 1280 × 720 parks behind the boot windows, downloading only its layer; DESK brings it in', async ({ page }) => {
    await countDrawingFrames(page);
    const paths = collectPaths(page);
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-state', 'covered', { timeout: 20_000 });
    await page.waitForTimeout(800);
    expect(paths.filter((p) => /DrawingField-|drawingFilm-/.test(p))).toEqual([]);
    expect(await drawingFrames(page)).toBe(0);
    await expect(page.locator('.wb-drawing-nav')).toHaveCount(0);
    await expect(page.locator('.wb-plate')).toContainText('01 OF 01 · SCALE 1:1');
    await desk(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-state', 'running', { timeout: 10_000 });
    await expect(drawing(page)).toHaveAttribute('data-drawing-mode', 'desk');
    await expect(page.locator('canvas[data-drawing-canvas]')).toHaveCount(1);
  });

  test('under reduced motion paints one still cover and never downloads the film', async ({ page }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.setViewportSize({ width: 1920, height: 1080 });
    await countDrawingFrames(page);
    const paths = collectPaths(page);
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-state', 'reduced-motion', { timeout: 20_000 });
    await expect(page.locator('.wb-drawing-chip')).toContainText(CREDIT, { timeout: 10_000 });
    await expect(page.locator('.wb-plate-slot')).toContainText('· STILL');
    await page.waitForTimeout(2000);
    expect(await drawingFrames(page)).toBe(0);
    expect(paths.filter((p) => /drawingFilm-/.test(p) || SHEET_CHUNK.test(p))).toEqual([]);
    // The still has no film to step through: no traverse, no row kept for one.
    await expect(page.locator('.wb-drawing-nav')).toHaveCount(0);
    await expect(page.locator('.wb-drawing-chip')).not.toHaveAttribute('data-nav', /.*/);
  });

  for (const size of [{ width: 1920, height: 1080, chunks: 2 }, { width: 1280, height: 720, chunks: 1 }]) {
    test(`on Data Saver at ${size.width} × ${size.height} downloads ${size.chunks} drawing chunk${size.chunks > 1 ? 's' : ''} and no film`, async ({ page }) => {
      await page.addInitScript(() => {
        Object.defineProperty(navigator, 'connection', {
          configurable: true,
          value: { saveData: true, effectiveType: '4g', addEventListener() {}, removeEventListener() {} },
        });
      });
      await page.setViewportSize({ width: size.width, height: size.height });
      const paths = collectPaths(page);
      await page.goto('/');
      await booted(page);
      // The same switch the Estate window reads: it waits on its consent.
      await expect(page.locator('#world')).toHaveAttribute('data-estate-phase', 'consent', { timeout: 20_000 });
      await expect(drawing(page)).toHaveAttribute('data-drawing-state', size.chunks > 1 ? 'save-data' : 'covered');
      if (size.chunks > 1) await expect(page.locator('.wb-drawing-chip')).toContainText(CREDIT, { timeout: 10_000 });
      await page.waitForTimeout(800);
      expect(paths.filter((p) => DRAWING_CHUNK.test(p) || SHEET_CHUNK.test(p))).toHaveLength(size.chunks);
      expect(paths.filter((p) => /drawingFilm-/.test(p))).toEqual([]);
      await expect(page.locator('.wb-drawing-nav')).toHaveCount(0);
    });
  }

  test('keeps the plain grid under ?mode=scan', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/?mode=scan');
    await booted(page);
    await page.waitForTimeout(800);
    await expect(drawing(page)).toHaveCount(0);
    await expect(page.locator('.wb-plate')).toContainText('01 OF 01 · SCALE 1:1');
  });

  test('switched off in the FX panel, it leaves the desk and the title plate as they were', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-mode', 'reading', { timeout: 20_000 });
    await page.getByRole('button', { name: 'FX, open optional effects lab' }).click();
    const toggle = page.getByRole('button', { name: /Estate drawings/ });
    await expect(toggle).toHaveAttribute('aria-pressed', 'true');
    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-pressed', 'false');
    await expect(drawing(page)).toHaveCount(0);
    await expect(page.locator('canvas[data-drawing-canvas]')).toHaveCount(0);
    await expect(page.locator('.wb-plate')).toContainText('01 OF 01 · SCALE 1:1');
  });

  test('has no serious accessibility violations at 1920 × 1080 with the drawing on, its traverse up and focused', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 20_000 });
    await expect(traverse(page)).toBeVisible();
    await traverse(page).locator('[aria-current="step"]').focus();
    const results = await new AxeBuilder({ page }).analyze();
    expect(results.violations.filter((v) => ['serious', 'critical'].includes(v.impact ?? ''))).toEqual([]);
  });

  test('at 1920 × 1080 the sheet traverse rides the chip in the drawing’s own region, over no window; Next re-issues the next sheet, then sleeps in its hold', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await countDrawingFrames(page);
    const errors = collectErrors(page);
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-mode', 'reading', { timeout: 20_000 });
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 20_000 });
    const bar = traverse(page);
    await expect(bar).toBeVisible();
    const place = await page.evaluate(() => {
      const box = (el: Element) => el.getBoundingClientRect();
      const nav = box(document.querySelector('[data-drawing-nav]')!);
      const canvas = box(document.querySelector('canvas[data-drawing-canvas]')!);
      const chip = box(document.querySelector('.wb-drawing-chip')!);
      const meets = (b: DOMRect) => nav.left < b.right && b.left < nav.right && nav.top < b.bottom && b.top < nav.bottom;
      return {
        inside: nav.left >= canvas.left - 0.5 && nav.right <= canvas.right + 0.5 && nav.top >= canvas.top - 0.5 && nav.bottom <= canvas.bottom + 0.5,
        onChip: [nav.left - chip.left, nav.top - chip.top, nav.width - chip.width].every((d) => Math.abs(d) < 0.5),
        overWindow: [...document.querySelectorAll<HTMLElement>('section[data-win]')].filter((w) => w.style.display !== 'none').some((w) => meets(box(w))),
        host: getComputedStyle(document.querySelector('.wb-drawing-nav')!).pointerEvents,
        hidden: document.querySelector('.wb-drawing-nav')!.closest('[aria-hidden="true"]') !== null,
      };
    });
    expect(place).toEqual({ inside: true, onChip: true, overWindow: false, host: 'none', hidden: false });
    const before = await sheet(page);
    const expected = await nextStation(page);
    expect(expected).toMatch(/^0\d$/);
    // A real pointer: nothing over the button may take the click.
    await bar.getByRole('button', { name: 'Next sheet' }).click();
    await expect(drawing(page)).not.toHaveAttribute('data-drawing-sheet', before!, { timeout: 1_500 });
    await expect(bar.locator('[aria-current="step"]')).toHaveText(expected!, { timeout: 1_500 });
    await expect(page.locator('.wb-plate-slot .wb-plate-lines span').first()).toHaveText(new RegExp(`^${expected} OF 0[67] · `));
    await expect(page.locator('.wb-drawing-nav [role="status"]')).toHaveText(new RegExp(`^Sheet ${expected} of 0[67], `));
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 3_000 });
    const frames = await drawingFrames(page);
    await page.waitForTimeout(1000);
    expect(await drawingFrames(page) - frames, 'drawing frames in 1 s of the hold a jump landed in').toBe(0);
    expect(errors).toEqual([]);
  });

  test('the sheet traverse is one Tab stop: Tab reaches it, → moves along it, Enter jumps', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 20_000 });
    await expect(traverse(page)).toBeVisible();
    const focused = () => page.evaluate(() => {
      const el = document.activeElement;
      return el?.closest('[data-drawing-nav]') ? el.getAttribute('aria-label') : null;
    });
    let at: string | null = null;
    for (let i = 0; i < 80 && at === null; i += 1) {
      await page.keyboard.press('Tab');
      at = await focused();
    }
    // It enters on the sheet on show.
    expect(at).toBe(await traverse(page).locator('[aria-current="step"]').getAttribute('aria-label'));
    await page.keyboard.press('ArrowRight');
    const moved = await focused();
    expect(moved).not.toBeNull();
    expect(moved).not.toBe(at);
    // From the last station, → is Next sheet; from any other, the next station: either jumps on Enter.
    const before = await sheet(page);
    if (moved !== 'Next sheet') {
      await page.keyboard.press('End');
      await page.keyboard.press('ArrowLeft');
      expect(await focused()).toBe('Next sheet');
    }
    await page.keyboard.press('Enter');
    await expect(drawing(page)).not.toHaveAttribute('data-drawing-sheet', before!, { timeout: 1_500 });
    expect(await focused()).toBe('Next sheet');
    // A second Tab leaves it: one stop.
    await page.keyboard.press('Tab');
    expect(await focused()).toBeNull();
  });

  test('with Pause all motion on, a jump changes the sheet in one paint: no drawing frame, the trolley’s transition off', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await countDrawingFrames(page);
    await page.goto('/');
    await booted(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 20_000 });
    await page.getByRole('button', { name: 'FX, open optional effects lab' }).click();
    const fx = page.getByRole('dialog', { name: 'Effects lab' });
    await fx.getByRole('button', { name: /^Pause all motion/ }).click();
    await expect(page.locator('html')).toHaveAttribute('data-motion-paused', 'true');
    await fx.getByRole('button', { name: 'Close' }).click();
    await expect(page.locator('.wb-plate-slot')).toContainText('· STILL');
    const frames = await drawingFrames(page);
    const before = await sheet(page);
    const expected = await nextStation(page);
    await traverse(page).getByRole('button', { name: 'Next sheet' }).click();
    await expect(drawing(page)).not.toHaveAttribute('data-drawing-sheet', before!);
    await expect(traverse(page).locator('[aria-current="step"]')).toHaveText(expected!);
    await expect(page.locator('.wb-plate-slot')).toContainText('· STILL');
    await page.waitForTimeout(500);
    expect(await drawingFrames(page) - frames, 'drawing frames for a jump while motion is paused').toBe(0);
    expect(await page.locator('.wb-drawing-nav-car').evaluate((car) => getComputedStyle(car).transitionDuration)).toBe('0s');
  });

  test('with the page’s own requestAnimationFrame unwrapped, an act still runs to its hold', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');
    await booted(page);
    await desk(page);
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'act', { timeout: 10_000 });
    await expect(drawing(page)).toHaveAttribute('data-drawing-phase', 'hold', { timeout: 15_000 });
    await expect(drawing(page)).not.toHaveAttribute('data-drawing-failed', /.*/);
  });
});
