import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { gunzipSync, gzipSync } from 'node:zlib';
import ts from 'typescript';
import { beforeAll, describe, expect, it } from 'vitest';
import { DRAWING_GENERATOR_FILES, drawingGeneratorDigest } from '../scripts/check-bundle.mjs';
import {
  buildDrawingSet, decodeRings, digestGenerator, drawingFiles, GENERATOR_SOURCES, LABEL_MIN_AREA, normaliseRing, readDrawingInputs,
  type DrawingInputs, type DrawingSet,
} from '../scripts/drawings/build';
import { ESTATE_CATALOGUE } from '../lib/estate/catalogue.generated';
import { parseNav, type EstateNav } from '../lib/estate/nav';
import { parsePack, type EstatePack } from '../lib/estate/schema';
import { CREDIT, DRAWING_SET_SCHEMA, DRAWING_SOURCE, LICENCE_URL, SITES } from '../lib/drawings/site.generated';
import type { DrawingSheet } from '../lib/drawings/types';

// The desk drawing set (docs/portfolio/desk-drawing-set.md §4): generated by
// scripts/drawings/build.ts from the committed estate pack and committed as
// lib/drawings/*.generated.ts. This file is its staleness gate (byte for byte)
// and pins what the derivations claim about the data: the line work traces to
// the pack's rooms, doors, stairs and lift landings, and every inference is the
// one the drawings label. check-bundle's checkDrawingSet is the deploy twin.

const root = fileURLToPath(new URL('..', import.meta.url));
const read = (rel: string) => readFileSync(path.join(root, rel), 'utf8');

let inputs: DrawingInputs;
let set: DrawingSet;
let pack: EstatePack;
const navs = new Map<string, EstateNav>();

beforeAll(() => {
  inputs = readDrawingInputs(root);
  set = buildDrawingSet(inputs);
  pack = parsePack(JSON.parse(read(`public${ESTATE_CATALOGUE.packUrl}`)));
  const dir = path.dirname(path.join(root, 'public', ESTATE_CATALOGUE.packUrl));
  for (const site of pack.sites) {
    navs.set(site.id, parseNav(JSON.parse(gunzipSync(readFileSync(path.join(dir, site.nav!.path))).toString('utf8')), site.id));
  }
}, 120_000);

type Pt = [number, number];
/** A ring as a key: rotated to start at its least (y, x) vertex. */
const ringKey = (pts: readonly Pt[]) => {
  let at = 0;
  pts.forEach((p, i) => { if (p[1] < pts[at][1] || (p[1] === pts[at][1] && p[0] < pts[at][0])) at = i; });
  return JSON.stringify([...pts.slice(at), ...pts.slice(0, at)]);
};

/** The relative modules a source imports for their values: `import type`, and an import of types alone, are erased by the build. */
const valueImports = (file: string, text: string): string[] => {
  const out: string[] = [];
  const visit = (node: ts.Node) => {
    if (ts.isImportDeclaration(node) && ts.isStringLiteral(node.moduleSpecifier)) {
      const clause = node.importClause;
      const bindings = clause?.namedBindings;
      if (!clause || (!clause.isTypeOnly && (clause.name !== undefined || !bindings || ts.isNamespaceImport(bindings)
        || !bindings.elements.length || bindings.elements.some((element) => !element.isTypeOnly)))) out.push(node.moduleSpecifier.text);
    } else if (ts.isExportDeclaration(node) && node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier)) {
      const clause = node.exportClause;
      if (!node.isTypeOnly && (!clause || !ts.isNamedExports(clause) || clause.elements.some((element) => !element.isTypeOnly))) out.push(node.moduleSpecifier.text);
    } else if (ts.isCallExpression(node) && node.expression.kind === ts.SyntaxKind.ImportKeyword && node.arguments[0] && ts.isStringLiteralLike(node.arguments[0])) {
      out.push(node.arguments[0].text);
    }
    ts.forEachChild(node, visit);
  };
  visit(ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true));
  return out.filter((specifier) => specifier.startsWith('.'));
};

/** A relative specifier as the bundler resolves it, repo-relative. */
const resolveModule = (from: string, specifier: string): string => {
  const base = path.posix.join(path.posix.dirname(from), specifier);
  const isFile = (rel: string) => { try { return statSync(path.join(root, rel)).isFile(); } catch { return false; } };
  const hit = [base, `${base}.ts`, `${base}.tsx`, `${base}/index.ts`].find(isFile);
  if (!hit) throw new Error(`${from}: cannot resolve ${specifier}`);
  return hit;
};

interface RawNav {
  stairs: { storey: string; flights: unknown[] }[];
  lifts: { name: string; served: string[]; landings: Record<string, unknown> }[];
}

/** The inputs with one site's nav file edited, stored, hashed and named as the pack tool would. */
const withNav = (id: string, edit: (raw: RawNav) => void): DrawingInputs => {
  const sha = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');
  const packJson = JSON.parse(new TextDecoder().decode(inputs.packBytes)) as { sites: { id: string; nav: { path: string; sha256: string; gzSha256: string } }[] };
  const site = packJson.sites.find((s) => s.id === id)!;
  const raw = JSON.parse(gunzipSync(inputs.files[site.nav.path]).toString('utf8')) as RawNav;
  edit(raw);
  const bytes = Buffer.from(JSON.stringify(raw));
  const stored = gzipSync(bytes);
  const files: Record<string, Uint8Array> = { ...inputs.files };
  delete files[site.nav.path];
  site.nav = { ...site.nav, path: site.nav.path.replace(/\.[0-9a-f]{8}\./, `.${sha(bytes).slice(0, 8)}.`), sha256: sha(bytes), gzSha256: sha(stored) };
  files[site.nav.path] = new Uint8Array(stored);
  return { ...inputs, packBytes: new TextEncoder().encode(JSON.stringify(packJson)), files };
};

const sheetStorey = (id: string, index: number) => SITES.find((s) => s.id === id)!.plan.indexOf(String(index));

const eachSheet = (fn: (id: string, sheet: DrawingSheet, storey: number) => void) => {
  for (const site of set.sites) set.sheets[site.id].forEach((sheet, i) => fn(site.id, sheet, sheetStorey(site.id, i)));
};

describe('desk drawing set — generated from the committed pack', () => {
  it('is up to date: regenerating gives the committed files byte for byte (else run `npm run drawings`)', () => {
    const files = drawingFiles(set);
    for (const file of files) expect(read(file.path), `${file.path} is stale: run \`npm run drawings\``).toBe(file.text);
    const onDisk = [
      ...readdirSync(path.join(root, 'lib', 'drawings')).filter((n) => n.endsWith('.generated.ts')).map((n) => `lib/drawings/${n}`),
      ...readdirSync(path.join(root, 'lib', 'drawings', 'sheets')).map((n) => `lib/drawings/sheets/${n}`),
    ].sort();
    expect(onDisk).toEqual(files.map((f) => f.path).sort());
  });

  it('names the pack, edition, commit and generator it came from', () => {
    expect(DRAWING_SET_SCHEMA).toBe('portfolio/drawing-set/1');
    expect(DRAWING_SOURCE.packName).toBe(path.posix.basename(ESTATE_CATALOGUE.packUrl));
    expect(DRAWING_SOURCE.edition).toBe(ESTATE_CATALOGUE.edition);
    expect(DRAWING_SOURCE.commit).toBe(ESTATE_CATALOGUE.commit);
    expect(DRAWING_SOURCE.dev).toBe(false);
    expect(DRAWING_SOURCE.packSha256).toBe(createHash('sha256').update(inputs.packBytes).digest('hex'));
    // The generator and the modules it imports, each as its path and LF text, NUL-separated.
    const generator = createHash('sha256');
    for (const rel of GENERATOR_SOURCES) generator.update(`${rel}\0${read(rel).replace(/\r\n/g, '\n')}\0`);
    expect(DRAWING_SOURCE.generatorDigest).toBe(generator.digest('hex'));
    expect(CREDIT).toBe(pack.licence.attribution);
    expect(CREDIT).toBe('Sample Town N5 © Rahul Mitra, CC BY 4.0, generated by Bonsai-Estate');
    expect(LICENCE_URL).toBe(pack.licence.url);
  });

  it('is deterministic, and its generator reads no clock, randomness or environment', () => {
    expect(drawingFiles(buildDrawingSet(inputs))).toEqual(drawingFiles(set));
    const source = read('scripts/drawings/build.ts');
    expect(source).not.toMatch(/\bDate\b/);
    expect(source).not.toMatch(/Math\.random/);
    expect(source).not.toMatch(/process\.env/);
  });

  it('digests the generator with every module it reaches through a value import, the same way check-bundle does', async () => {
    // Type-only imports are erased by the build, so they shape nothing and do not count.
    expect(valueImports('x.ts', [
      "import type { A } from './a';", "import { type B } from './b';", "import { c, type D } from './c';",
      "export type { E } from './e';", "export { f } from './f';", "import './g';", "import * as h from './h';",
      "import i from './i.json';", "import { j } from 'vitest';", "const k = () => import('./k');",
    ].join('\n'))).toEqual(['./c', './f', './g', './h', './i.json', './k']);
    const closure: string[] = [];
    const visit = (rel: string) => {
      if (closure.includes(rel)) return;
      closure.push(rel);
      if (/\.tsx?$/.test(rel)) for (const specifier of valueImports(rel, read(rel))) visit(resolveModule(rel, specifier));
    };
    visit('scripts/drawings/build.ts');
    expect(GENERATOR_SOURCES).toEqual([closure[0], ...closure.slice(1).sort()]);
    expect(DRAWING_GENERATOR_FILES).toEqual(GENERATOR_SOURCES);
    expect(await drawingGeneratorDigest()).toBe(DRAWING_SOURCE.generatorDigest);
    // Insensitive to the checkout's line endings; sensitive to every file, not only build.ts.
    const sources = Object.fromEntries(GENERATOR_SOURCES.map((rel) => [rel, read(rel)]));
    const crlf = Object.fromEntries(Object.entries(sources).map(([rel, text]) => [rel, text.replace(/\r?\n/g, '\r\n')]));
    expect(digestGenerator(crlf)).toBe(digestGenerator(sources));
    expect(digestGenerator({ ...sources, 'lib/estate/plan.ts': `${sources['lib/estate/plan.ts']}\n` })).not.toBe(digestGenerator(sources));
    expect(() => digestGenerator({ ...sources, 'lib/estate/ground.ts': undefined as unknown as string })).toThrow(/lib\/estate\/ground\.ts was not read/);
  });

  it('fails generation when a typical storey has other flights or lift stops than the typical plan it is drawn by', () => {
    // The edit path alone changes nothing the generator checks.
    expect(drawingFiles(buildDrawingSet(withNav('BLK_501', () => {}))).slice(1)).toEqual(drawingFiles(set).slice(1));
    // L7 of BLK 501 is one of the 19 storeys its TYP sheet (drawn from L2) stands for.
    expect(() => buildDrawingSet(withNav('BLK_501', (raw) => { raw.stairs.find((s) => s.storey === 'L7')!.flights.pop(); })))
      .toThrow('BLK_501 TYP: L7 has 3 stair flights up, the typical plan 4');
    expect(() => buildDrawingSet(withNav('BLK_501', (raw) => { delete raw.lifts[0].landings.L7; })))
      .toThrow('BLK_501 TYP: Lift 1 lands on L2 but not on L7');
    expect(() => buildDrawingSet(withNav('BLK_501', (raw) => { raw.lifts.push({ name: 'Lift 9', served: ['L7'], landings: { L7: { xy: [0, 0], facing: [1, 0] } } }); })))
      .toThrow('BLK_501 TYP: Lift 9 lands on L7 but not on L2');
  });

  it('draws every room of every sheet exactly as the nav file outlines it', () => {
    eachSheet((id, sheet, storey) => {
      const nav = navs.get(id)!;
      const expected = nav.rooms[storey].map((room) => ringKey(normaliseRing(room.poly, room.name))).sort();
      expect(decodeRings(sheet.rings).map(ringKey).sort(), `${id} ${sheet.key}`).toEqual(expected);
      expect(sheet.codes.split('|')).toHaveLength(expected.length);
      expect(sheet.labels.split('|')).toHaveLength(expected.length);
    });
    for (const site of set.sites) {
      const fp = pack.sites.find((s) => s.id === site.id)!.footprint;
      expect(ringKey(decodeRings(site.fp)[0])).toBe(ringKey(normaliseRing(fp, site.id)));
    }
  });

  it('covers every storey: 245 in all, typical storeys drawn once, the hawker centre’s empty roof drawn by no sheet', () => {
    expect(set.sites.reduce((n, s) => n + s.plan.length, 0)).toBe(245);
    expect(set.sites.reduce((n, s) => n + s.flats, 0)).toBe(1206);
    expect(set.sites.map((s) => `${s.id}:${s.sheets.join(',')}`)).toEqual([
      ...['501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512'].map((n) => `BLK_${n}:L1,TYP,RF`),
      'MSCP_513:L1,TYP,RF', 'NC_514:L1,L2',
    ]);
    expect(SITES.find((s) => s.id === 'BLK_501')!.plan).toBe(`0${'1'.repeat(19)}2`);
    expect(SITES.find((s) => s.id === 'NC_514')!.plan).toBe('01-');
    expect(set.sheets.BLK_501[1]).toMatchObject({ key: 'TYP', storeys: 'L2–L20', count: 19, h: 260 });
  });

  it('draws doors as openings between their measured faces, never as swings', () => {
    let doors = 0;
    const depths: Record<number, number> = {};
    eachSheet((id, sheet, storey) => {
      expect(sheet.doors.length / 6, `${id} ${sheet.key}`).toBe(navs.get(id)!.doors[storey].length);
      for (let k = 0; k < sheet.doors.length; k += 6) {
        const depth = sheet.doors[k + 5] - sheet.doors[k + 4];
        depths[depth] = (depths[depth] ?? 0) + 1;
        doors += 1;
      }
    });
    expect(doors).toBe(854);
    expect(depths).toEqual({ 10: 455, 15: 2, 20: 323, 25: 71, 26: 3 });
  });

  it('draws each stair from its flights, the flights rising exactly one storey, labelled by the stored riser', () => {
    const labels = new Set<string>();
    eachSheet((id, sheet) => {
      const sums = new Map<number, { risers: number; riser: number }>();
      for (let k = 0; k < sheet.flights.length; k += 9) {
        const n = sheet.flights[k];
        const row = sums.get(n) ?? { risers: 0, riser: sheet.flights[k + 7] };
        row.risers += sheet.flights[k + 6];
        sums.set(n, row);
      }
      for (const { risers, riser } of sums.values()) labels.add(`${risers} R × ${riser}`);
      expect(sums.size, `${id} ${sheet.key}`).toBeGreaterThan(0);
    });
    expect([...labels].sort()).toEqual(['16 R × 175', '18 R × 167', '21 R × 171', '24 R × 175']);
    for (const nav of navs.values()) {
      for (const stair of nav.stairs) {
        const span = stair.flights[stair.flights.length - 1].end[2] - stair.flights[0].start[2];
        expect(Math.abs(span - (stair.toFfl - stair.fromFfl))).toBeLessThan(0.001);
      }
    }
  });

  it('infers lift cores only behind lift landings (or lined up with them on a roof), and says the rest is not a room', () => {
    const cores = (id: string) => set.sheets[id].map((s) => s.cores.length / 6);
    for (const id of ['BLK_501', 'BLK_502', 'BLK_503', 'BLK_504', 'BLK_505', 'BLK_506', 'BLK_512']) expect(cores(id)).toEqual([1, 1, 1]);
    for (const id of ['BLK_507', 'BLK_508', 'BLK_510', 'BLK_511']) expect(cores(id)).toEqual([2, 2, 2]);
    expect(cores('BLK_509')).toEqual([3, 3, 3]);
    expect(cores('MSCP_513')).toEqual([1, 1, 1]);
    expect(cores('NC_514')).toEqual([1, 0]);
    // Every block roof's core lines up with the typical floor's.
    for (const site of set.sites.filter((s) => s.kind === 'block')) {
      const [, typ, rf] = set.sheets[site.id];
      expect(rf.lifts).toEqual([]);
      for (let k = 0; k < rf.cores.length; k += 6) expect(rf.cores[k + 5]).toBe(1);
      expect(rf.cores.filter((_, i) => i % 6 < 5)).toEqual(typ.cores.filter((_, i) => i % 6 < 5));
    }
    // Voids: only the car park's ramp box and two small plant spaces, on its decks.
    eachSheet((id, sheet) => {
      expect(sheet.voids.length > 0, `${id} ${sheet.key}`).toBe(id === 'MSCP_513' && sheet.key !== 'RF');
    });
    expect(set.stats.voids['MSCP_513 TYP']).toEqual([7, 9.3, 364.3]);
    expect(set.sheets.MSCP_513[1].voids.slice(-4)).toEqual([-1320, 3620, 1320, 5000]);
    expect(set.stats.partial).toEqual(['NC_514 L2']);
    expect(set.sheets.NC_514[1]).toMatchObject({ partial: true, cores: [], voids: [], bands: [] });
  });

  it('leaves no wall fill in a core, a void or an open-air strip, and none of them touches a room', () => {
    eachSheet((id, sheet) => {
      const rooms = decodeRings(sheet.rings);
      const inside = (x: number, y: number, pts: readonly Pt[]) => {
        let hit = false;
        for (let i = 0, j = pts.length - 1; i < pts.length; j = i, i += 1) {
          if ((pts[i][1] > y) !== (pts[j][1] > y) && x < ((pts[j][0] - pts[i][0]) * (y - pts[i][1])) / (pts[j][1] - pts[i][1]) + pts[i][0]) hit = !hit;
        }
        return hit;
      };
      const rects = [
        ...Array.from({ length: sheet.cores.length / 6 }, (_, k) => sheet.cores.slice(6 * k, 6 * k + 4)),
        ...Array.from({ length: sheet.voids.length / 4 }, (_, k) => sheet.voids.slice(4 * k, 4 * k + 4)),
        ...Array.from({ length: sheet.bands.length / 4 }, (_, k) => sheet.bands.slice(4 * k, 4 * k + 4)),
      ];
      for (const [x0, y0, x1, y1] of rects) {
        for (const [fx, fy] of [[0.5, 0.5], [0.1, 0.1], [0.9, 0.9], [0.1, 0.9], [0.9, 0.1]]) {
          const x = x0 + fx * (x1 - x0);
          const y = y0 + fy * (y1 - y0);
          expect(rooms.some((pts) => inside(x, y, pts)), `${id} ${sheet.key} [${x0},${y0},${x1},${y1}]`).toBe(false);
        }
      }
    });
  });

  it('marks the footprint beside an open-air strip as a slab edge, along the footprint itself', () => {
    let slabs = 0;
    eachSheet((id, sheet) => {
      const fp = decodeRings(SITES.find((s) => s.id === id)!.fp)[0];
      for (let k = 0; k < sheet.slabs.length; k += 4) {
        const [axis, line, lo, len] = sheet.slabs.slice(k, k + 4);
        const onEdge = fp.some((a, i) => {
          const b = fp[(i + 1) % fp.length];
          return axis === 0
            ? a[1] === line && b[1] === line && Math.min(a[0], b[0]) <= lo && Math.max(a[0], b[0]) >= lo + len
            : a[0] === line && b[0] === line && Math.min(a[1], b[1]) <= lo && Math.max(a[1], b[1]) >= lo + len;
        });
        expect(onEdge, `${id} ${sheet.key} slab ${[axis, line, lo, len]}`).toBe(true);
        slabs += 1;
      }
    });
    expect(slabs).toBeGreaterThan(100);
  });

  it('builds massing only to the roof level, plus the roof’s enclosed rooms by their clear height', () => {
    for (const site of SITES) {
      const roof = navs.get(site.id)!.rooms.at(-1)!.filter((room) => !room.ext);
      expect(decodeRings(site.caps)).toHaveLength(roof.length);
      expect(site.capsH).toEqual(roof.map((room) => Math.round(room.h * 100)));
      expect(site.top).toBe(Math.round(pack.sites.find((s) => s.id === site.id)!.roofTop * 100));
    }
    expect(SITES.find((s) => s.id === 'BLK_501')!.capsH).toEqual([300, 300]);
    expect(SITES.find((s) => s.id === 'NC_514')!.capsH).toEqual([]);
  });

  it('skips only the car park roof’s stair islands from the wall fill', () => {
    eachSheet((id, sheet) => expect(sheet.skip.length, `${id} ${sheet.key}`).toBe(id === 'MSCP_513' && sheet.key === 'RF' ? 2 : 0));
  });

  it('keeps label anchors for named rooms of at least 9 m², and counts the car park’s lots instead of labelling them', () => {
    eachSheet((id, sheet, storey) => {
      const labels = sheet.labels.split('|');
      const rooms = navs.get(id)!.rooms[storey];
      const big = new Set(rooms.filter((room) => room.area >= LABEL_MIN_AREA).map((room) => ringKey(normaliseRing(room.poly, room.name))));
      const rings = decodeRings(sheet.rings);
      for (let k = 0; k < sheet.anchors.length; k += 3) {
        const i = sheet.anchors[k];
        expect(labels[i]).not.toBe('');
        expect(big.has(ringKey(rings[i]))).toBe(true);
      }
    });
    expect(set.sheets.MSCP_513.map((s) => s.lots)).toEqual([[123, 51], [126, 51], [0, 0]]);
    expect(set.sheets.MSCP_513[1].labels.split('|').filter(Boolean)).not.toContainEqual(expect.stringMatching(/lot/i));
  });

  it('carries no field the data does not hold: no swing, hinge, glazing, column or parapet', () => {
    const keys = ['anchors', 'bands', 'codes', 'cores', 'count', 'doors', 'ext', 'flights', 'groups', 'h', 'hx', 'key', 'labels',
      'lifts', 'lots', 'partial', 'rings', 'shared', 'skip', 'slabs', 'storeys', 'units', 'voids'];
    eachSheet((_id, sheet) => expect(Object.keys(sheet).sort()).toEqual(keys));
    const text = drawingFiles(set).map((f) => f.text).join('\n');
    expect(text).not.toMatch(/\b(swing|hinge|arc|window|glazing|column|parapet)\w*:/i);
  });

  it('traces kerbs from the ground raster: the road edge, 3.39 km', () => {
    expect(set.stats.kerbMetres).toBe(3388);
  });

  it('stays within its budgets: the site module and each building’s module, raw and gzipped', () => {
    // Measured at generation: site 12,808 B / 3,298 B gz; buildings 7.2–20.1 KB / 2.5–4.8 KB gz;
    // 48.6 KB gz in all. Each cap is the measure plus about 10 %.
    const gz = (text: string) => gzipSync(text, { level: 9 }).length;
    let total = 0;
    for (const file of drawingFiles(set)) {
      total += gz(file.text);
      if (file.path.endsWith('site.generated.ts')) {
        expect(file.text.length).toBeLessThanOrEqual(14_500);
        expect(gz(file.text)).toBeLessThanOrEqual(3_700);
      } else if (file.path.includes('/sheets/')) {
        expect(file.text.length, file.path).toBeLessThanOrEqual(22_000);
        expect(gz(file.text), file.path).toBeLessThanOrEqual(5_400);
      }
    }
    expect(total).toBeLessThanOrEqual(54_000);
  });
});
