// Generated by scripts/drawings/build.ts (npm run drawings) from the committed estate pack: one lazy chunk per building.
// Do not edit: regenerate it (docs/portfolio/desk-drawing-set.md). tests/drawing-set.test.ts and
// scripts/check-bundle.mjs fail while it is stale.

import type { DrawingSheet } from './types';

export interface SheetModule { DRAWING_SHEET_SCHEMA: string; SITE_ID: string; SHEETS: readonly DrawingSheet[] }

export const SHEET_LOADERS: Readonly<Record<string, () => Promise<SheetModule>>> = {
  BLK_501: () => import('./sheets/BLK_501.generated'),
  BLK_502: () => import('./sheets/BLK_502.generated'),
  BLK_503: () => import('./sheets/BLK_503.generated'),
  BLK_504: () => import('./sheets/BLK_504.generated'),
  BLK_505: () => import('./sheets/BLK_505.generated'),
  BLK_506: () => import('./sheets/BLK_506.generated'),
  BLK_507: () => import('./sheets/BLK_507.generated'),
  BLK_508: () => import('./sheets/BLK_508.generated'),
  BLK_509: () => import('./sheets/BLK_509.generated'),
  BLK_510: () => import('./sheets/BLK_510.generated'),
  BLK_511: () => import('./sheets/BLK_511.generated'),
  BLK_512: () => import('./sheets/BLK_512.generated'),
  MSCP_513: () => import('./sheets/MSCP_513.generated'),
  NC_514: () => import('./sheets/NC_514.generated'),
};
