// The desk drawing set's data contract (docs/portfolio/desk-drawing-set.md §4).
//
// Every value here is generated by scripts/drawings/build.ts from the committed
// estate pack (public/estate/v1.2: pack.json, nav/*.json.gz, site/ground) and
// committed as lib/drawings/*.generated.ts, so the desk draws without a single
// request under /estate/. Types only: the runtime drawing code imports nothing
// from lib/estate but types, or Rollup would put an Estate module in a shared
// chunk (vite.config.ts names that chunk estate-shared-*).
//
// Units: integer centimetres, x east, y north, unless a field says otherwise.
// Plans are block-local (the nav files' frame); the site plan is the estate
// frame (block-local + `at`; the pack has no rotated sites).

/**
 * Rings, concatenated. Each ring is `n, f, dx0, dy0, d1 … d(n−2)`: n vertices
 * (even: every edge is axis-aligned and consecutive edges alternate), f the
 * axis of the first edge (0 = along x), (dx0, dy0) the first vertex relative to
 * the previous ring's first vertex (the first ring's to the origin), then the
 * signed lengths of the first n−2 edges, alternating axis. The last two edges
 * close the ring. Counter-clockwise. decode.ts expands them.
 */
export type RingData = readonly number[];

export interface DrawingSource {
  /** pack.<h8>.json the set was generated from (the catalogue's packUrl basename). */
  packName: string;
  /** sha256 of that file's bytes. */
  packSha256: string;
  edition: string;
  /** Bonsai-Estate commit the pack was built from. */
  commit: string;
  /** A dev pack (never shipped; check-bundle refuses it on CI/Vercel). */
  dev: boolean;
  /**
   * sha256 over the generator's sources (GENERATOR_SOURCES in scripts/drawings/build.ts:
   * build.ts and every module it reaches through a relative value import), each as its
   * path and its LF text.
   */
  generatorDigest: string;
}

/** The poster camera, verbatim from pack.views.aerialNE, plus the poster's pixel size. */
export interface DrawingPoster {
  eye: readonly [number, number, number];
  quat: readonly [number, number, number, number];
  vfovDeg: number;
  shift: readonly [number, number];
  aspect: number;
  w: number;
  h: number;
}

export type DrawingSiteKind = 'block' | 'mscp' | 'nc';

export interface DrawingSite {
  /** 'BLK_501'. */
  id: string;
  /** The pack's own name: 'Blk 501', 'Multi-storey car park 513'. */
  name: string;
  /** The caption form: 'BLK 501', 'MSCP 513', 'NC 514'. */
  short: string;
  kind: DrawingSiteKind;
  /** 'PT4', 'SL', 'LB', 'SL (EA)', or null. */
  typology: string | null;
  /** Estate frame position of the block-local origin, cm. */
  at: readonly [number, number];
  /** Footprint, one ring record, block-local. */
  fp: RingData;
  /** FFL per storey, bottom-up, cm. Tags are L1 … L(n−1), RF. */
  ffl: readonly number[];
  /** The pack's roofTop, cm: a level tag ("MODEL TOP") only, never massing. */
  top: number;
  /** Non-open-air rooms on the roof (stair cores): rings, and each one's clear height, cm. */
  caps: RingData;
  capsH: readonly number[];
  /** Sheet keys in order: 'L1', 'TYP', 'RF', 'L2'. */
  sheets: readonly string[];
  /** Per storey, the index of the sheet that draws it, or '-' for none. */
  plan: string;
  /** Flats in the building. */
  flats: number;
  /** 'L1–L20 + RF'. */
  levels: string;
}

/**
 * One plan sheet: a storey (or the typical storey, drawn once for all of them)
 * cut as a plan. Rings are in pen order (the order DRAW-IN reveals them), each
 * entered at the vertex nearest the previous pen-up.
 */
export interface DrawingSheet {
  /** 'L1', 'TYP', 'RF', 'L2'. */
  key: string;
  /** The storey tags it covers: 'L2–L20', 'L1'. */
  storeys: string;
  /** How many storeys it covers. */
  count: number;
  /** Commonest clear height on the sheet, cm. */
  h: number;
  /** Rooms (spaces), in pen order. */
  rings: RingData;
  /** [ring, h] pairs where a room's clear height differs from `h`. */
  hx: readonly number[];
  /** Ring indices of open-air rooms (void deck, roof deck). */
  ext: readonly number[];
  /** Ring indices left out of the wall fill: rooms wholly inside another room. */
  skip: readonly number[];
  /** Room codes ('B2', 'LOBBY', '' for a lot), '|'-joined, parallel to the rings. */
  codes: string;
  /** Room labels ('Bedroom 2', '' for a lot), '|'-joined, parallel to the rings. */
  labels: string;
  /** Label anchors of the rooms that may carry a label (named, ≥ 9 m²): [ring, x, y] (plan.ts roomAnchor). */
  anchors: readonly number[];
  /** Pen groups in order: ring counts. Group 0 is the rooms outside any flat. */
  groups: readonly number[];
  /** Group names, '|'-joined: '' for group 0, then unit numbers ('101'). */
  units: string;
  /** Space boundaries with no wall between them: [axis, k, lo, len] (axis 0 = along x at y = k). */
  shared: readonly number[];
  /** Openings: [x, y, axis, w, o1, o2]: centre on the wall line, the wall's axis, width, the faces' offsets across it. */
  doors: readonly number[];
  /** Stair flights, mm: [stair, sx, sy, ex, ey, width, risers, riser, dir] (dir 1 up from this storey, −1 arriving). */
  flights: readonly number[];
  /** Lift landings on this storey: [lift, x, y, fx, fy] (fx, fy the unit facing out of the car). */
  lifts: readonly number[];
  /** Inferred lift cores: [x0, y0, x1, y1, lifts, alignedBelow]. */
  cores: readonly number[];
  /** Unroomed regions too thick to be walls and not a lift core: [x0, y0, x1, y1]. */
  voids: readonly number[];
  /** Strips between an open-air room and the footprint, disjoint: [x0, y0, x1, y1]. No wall fill there. */
  bands: readonly number[];
  /** The footprint beside those strips, a slab edge rather than a wall: [axis, k, lo, len]. */
  slabs: readonly number[];
  /** Most of the footprint has no rooms on this storey (NC 514's L2): no wall fill, the footprint dashed. */
  partial: boolean;
  /** Car and motorcycle lots on the sheet (the car park), counted rather than labelled. */
  lots: readonly [number, number];
}

/** Kerb lines, estate frame, 25 cm units: per polyline `n, x0, y0, dx1, dy1, …`. */
export type PolylineData = readonly number[];
