// pack.<h8>.json (plan §6.4; lib/estate/schema.ts is the contract and its
// parsePack the gate) and lib/estate/catalogue.generated.ts (§6.3).

import { gzipDeterministic, sha256 } from './files.mjs';

export const PACK_SCHEMA = 'portfolio/estate-pack/1';
/** The edition this tool builds (schema.ts ESTATE_PACK_EDITION; the release tag and the public/estate folder). */
export const EDITION = 'v1.2';
export const REPO = 'https://github.com/Rah-Rah-Mitra/Bonsai-Estate';
export const FRAME = 'three world = estate (x, z, -y); building root = (at.x, 0, -at.y); glTF block-local Y-up; walk/nav block-local Z-up';
export const ATTRIBUTION = 'Sample Town N5 © Rahul Mitra, CC BY 4.0, generated by Bonsai-Estate';
export const CLASS_ORDER = ['poster', 's0', 'f', 'd', 'i', 'w', 'nav', 'ground'];

const mm = (v) => { const r = Math.round(v * 1000) / 1000; return r === 0 ? 0 : r; };

/** A storey's display name: 'Level 5', 'Roof'. */
export const storeyName = (tag) => (tag === 'RF' ? 'Roof' : `Level ${tag.slice(1)}`);

/** Half the bounds' diagonal, rounded up to the millimetre: parsePack requires it to enclose them. */
export const boundsRadius = ([lo, hi]) => Math.ceil(0.5 * Math.hypot(hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]) * 1000) / 1000;

/**
 * Serialises pack.json, solving totals.stage0Bytes (and totals.bytes) for the
 * file's own size: both include pack.json, whose size depends on them. The
 * loop only ever raises them, so it ends; the result is the smallest fixed
 * point. Returns { text, bytes: Buffer, gzBytes }.
 */
export const serialisePack = (pack, stage0Files, allFiles) => {
  let stage0 = stage0Files; let total = allFiles;
  for (let round = 0; round < 16; round += 1) {
    pack.totals.stage0Bytes = stage0;
    pack.totals.bytes = total;
    const text = `${JSON.stringify(pack)}\n`;
    const bytes = Buffer.from(text, 'utf8');
    const gz = gzipDeterministic(bytes).length;
    const nextStage0 = Math.max(stage0, stage0Files + gz);
    const nextTotal = Math.max(total, allFiles + bytes.length);
    if (nextStage0 === stage0 && nextTotal === total) return { text, bytes, gzBytes: gz };
    stage0 = nextStage0; total = nextTotal;
  }
  throw new Error('pack.json totals did not settle');
};

/**
 * The catalogue module's source (≤ 6 KB; checked by the caller). Each site
 * carries its per-class bytes as `{ facade: { bytes } … }`, so a site is an
 * EstateEnterFiles (lib/estate/policy.ts) as it stands. `posterSize` is the
 * 1600 px poster's own size, as encodePosters measured it.
 */
/**
 * 'L1–L16 + RF': a site's storeys as the registry prints them. Written into
 * the catalogue as one string per site, so the main bundle carries no storey
 * arrays (lib/estate/ids.ts holds the full tables for the code that needs them).
 */
export const storeyRange = (storeys) => {
  const levels = storeys.filter((tag) => tag !== 'RF');
  const range = levels.length > 1 ? `${levels[0]}–${levels[levels.length - 1]}` : (levels[0] ?? '');
  return storeys.includes('RF') ? `${range} + RF` : range;
};

/**
 * lib/estate/catalogue.generated.ts: what the main bundle reads before any
 * engine exists, and nothing more (every byte here ships on every page view,
 * under the 510,000 B main-bundle cap): the pack's URL and provenance flag, the
 * poster, the facts, one line per site, and the two byte totals the consent
 * label counts (stage 0, ΣF). Per-site and per-class file sizes live in
 * pack.json, which the engine reads; P5's Enter labels take them from there.
 */
export const catalogueSource = ({ pack, packUrl, posters, posterSize, sites }) => {
  const poster = (name) => posters.find((p) => p.path.includes(`/${name}.`));
  const url = (p) => `/estate/${pack.edition}/${p.path}`;
  const webp1600 = poster('aerial-1600'); const webp800 = posters.find((p) => /aerial-800\.[0-9a-f]{8}\.webp$/.test(p.path)); const jpg800 = posters.find((p) => p.path.endsWith('.jpg'));
  const bytes = { stage0: pack.totals.stage0Bytes, f: pack.totals.byClass.f ?? 0 };
  const q = (v) => JSON.stringify(v);
  const siteLines = sites.map((s) => `    { id: ${q(s.id)}, name: ${q(s.name)}, kind: ${q(s.kind)}, typology: ${q(s.typology)}, heightM: ${q(s.heightM)}, levels: ${q(storeyRange(s.storeys))} },`);

  const lines = [
    '// Generated by scripts/estate/pack.mjs from the pack it describes. Do not edit:',
    '// rebuild the pack instead (docs/portfolio/estate-pack.md).',
    `// ${pack.source.dev ? 'DEV PACK — built with --dev-src, provenance unchecked; never commit or publish.' : `Bonsai-Estate ${pack.source.tag} @ ${pack.source.commit}.`}`,
    '',
    'export const ESTATE_CATALOGUE = {',
    `  edition: ${q(pack.edition)},`,
    `  packUrl: ${q(packUrl)},`,
    `  commit: ${q(pack.source.commit)},`,
    `  dev: ${pack.source.dev === true},`,
    posters.length ? `  poster: { src: ${q(url(jpg800))}, srcSet: ${q(`${url(webp800)} 800w, ${url(webp1600)} 1600w`)}, w: ${posterSize?.w ?? 1600}, h: ${posterSize?.h ?? 1200}, alt: ${q('Still render of Sample Town N5 from the north-east: a generated sample HDB neighbourhood, not a real town.')} },` : '  poster: null,',
    `  flats: ${pack.estate.flats},`,
    `  storeys: ${pack.estate.storeys},`,
    '  sites: [',
    ...siteLines,
    '  ],',
    `  bytes: ${q(bytes)},`,
    '} as const;',
    '',
    'export type EstateCatalogue = typeof ESTATE_CATALOGUE;',
    '',
  ];
  return lines.join('\n');
};

export { mm };
export const packFileName = (bytes) => `pack.${sha256(bytes).slice(0, 8)}.json`;
